{
 "title": "ICP Deployments",
 "description": "Dashboard that shows how many deployments occurred by namespace or in the cluster and your workload",
 "tags": [
  "k8s",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\"} , namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{job=\"kubernetes-service-endpoints-with-tls\", namespace=\"$namespace\"} , deployment)"
   },
   {
    "name": "replicaset",
    "label": "ReplicaSet",
    "query": "query_result(topk(1, kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\", namespace=\"$namespace\", replicaset=~\"$deployment-[0-9a-fA-F]+\"}))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Latest Deployment $namespace / $replicaset</span>\n</div>"
  },
  {
   "title": "Last  deployments in $namespace / $deployment",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sort_desc(sum((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\", namespace=\"$namespace\", replicaset=~\"$deployment-[0-9a-fA-F]+\"}) * 1000) by (replicaset, namespace))"
    }
   ]
  },
  {
   "title": "Deployments in $deployment (last day)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\",namespace=\"$namespace\",replicaset=~\"$deployment.*\"} > time() - 86400))"
    }
   ]
  },
  {
   "title": "Deployments in $deployment (7 days)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\",namespace=\"$namespace\",replicaset=~\"$deployment.*\"} > time() - 604800))"
    }
   ]
  },
  {
   "title": "Deployments in $deployment (last month)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\",namespace=\"$namespace\",replicaset=~\"$deployment.*\"} > time() - 2592000))"
    }
   ]
  },
  { "title": "Last deployments in $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last Deployments in $namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\",namespace=\"$namespace\"} > time() - 604800) * 1000) by (replicaset,namespace))"
    }
   ]
  },
  {
   "title": "Deployments in $namespace (last day)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\",namespace=\"$namespace\"} > time() - 86400))"
    }
   ]
  },
  {
   "title": "Deployments in $namespace (last 7 days)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\",namespace=\"$namespace\"} > time() - 604800))"
    }
   ]
  },
  {
   "title": "Deployments in $namespace (last month)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\",namespace=\"$namespace\"} > time() - 2592000))"
    }
   ]
  },
  { "title": "Last deployments in Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Last Deployments in Cluster",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(((kube_replicaset_created{job=\"kubernetes-service-endpoints-with-tls\"} > time() - 604800) * 1000)) by (replicaset, namespace)",
     "legendFormat": "{{ namespace }} - {{ replicaset }}"
    },
    {
     "expr": "sum(((kube_statefulset_created{job=\"kubernetes-service-endpoints-with-tls\"} > time() - 604800) * 1000)) by (statefulset, namespace)",
     "legendFormat": "{{ namespace }} - {{ statefulset }}"
    },
    {
     "expr": "sum(((kube_daemonset_created{job=\"kubernetes-service-endpoints-with-tls\"} > time() - 604800) * 1000)) by (daemonset, namespace)",
     "legendFormat": "{{ namespace }} - {{ daemonset }}"
    }
   ]
  },
  {
   "title": "Deployments in last day",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(({__name__=~\"kube_replicaset_created|kube_statefulset_created|kube_daemonset_created\", job=\"kubernetes-service-endpoints-with-tls\"} > time() - 86400))"
    }
   ]
  },
  {
   "title": "Deployments in last 7 days",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(({__name__=~\"kube_replicaset_created|kube_statefulset_created|kube_daemonset_created\", job=\"kubernetes-service-endpoints-with-tls\"} > time() - 604800))"
    }
   ]
  },
  {
   "title": "Deployments in last month",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(({__name__=~\"kube_replicaset_created|kube_statefulset_created|kube_daemonset_created\", job=\"kubernetes-service-endpoints-with-tls\"} > time() - 2592000))"
    }
   ]
  }
 ]
}