{
 "title": "K8s / Node",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(node_boot_time_seconds{job=\"node-exporter-endpoints-with-tls\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_load1{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "max(node_load5{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "max(node_load15{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Usage Per Core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter-endpoints-with-tls\", mode!=\"idle\", instance=\"$instance\"}[5m])) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter-endpoints-with-tls\", mode!=\"idle\", instance=\"$instance\"}[2m])) ) * 100\n",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{job=\"node-exporter-endpoints-with-tls\", mode!=\"idle\", instance=\"$instance\"}[2m]))) * 100\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n  - node_memory_Cached_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n    - node_memory_Cached_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{job=\"node-exporter-endpoints-with-tls\",  instance=\"$instance\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node:node_filesystem_usage:\n", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"node-exporter-endpoints-with-tls\", instance=\"$instance\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}